name: CI/CD Pipeline

# Exécution du workflow à chaque push ou pull request sur la branche principale
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Définir les jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code (checkout)
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: ''

      # Étape 3 : Compiler le projet
      - name: Build with Maven
        run: mvn clean compile

      # Étape 4 : Lancer les tests
      - name: Run tests
        run: mvn test

  deploy:
    needs: build  # Dépend du job de build
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Afficher un message simulant un déploiement
      - name: Simulate Deployment
        run: echo "Déploiement réussi sur l'environnement de staging ! 🎉"
